---
# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  ansible.builtin.set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Passenger repository setup.
- name: Add Passenger apt key.
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 561F9B9CAC40B2F7
    state: present

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600
  when: ansible_os_family == 'Debian'

- name: Ensure build dependencies are installed (Debian).
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - apt-transport-https
    - curl
    - dirmngr
    - gnupg
    - ca-certificates
  when: ansible_os_family == 'Debian'

- name: Add Phusion apt repo.
  ansible.builtin.apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main'
    state: present
    update_cache: true

- name: Install Nginx and Passenger.
  ansible.builtin.apt:
    name:
      - nginx
      - libnginx-mod-http-passenger
    state: present

- name: Ensure passenger module is enabled.
  ansible.builtin.file:  # noqa risky-file-permissions
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link

# Nginx and passenger configuration.
- name: Copy Nginx configuration into place.
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Restart nginx

- name: Configure passenger virtual host.
  ansible.builtin.template:
    src: passenger.j2
    dest: /etc/nginx/sites-available/passenger
    mode: '0644'
  notify: Restart nginx

- name: Ensure passenger virtual host is enabled.
  ansible.builtin.file:  # noqa risky-file-permissions
    src: /etc/nginx/sites-available/passenger
    dest: /etc/nginx/sites-enabled/passenger
    state: link

- name: Ensure default virtual host is removed.
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_remove_default_vhost
  notify: Restart nginx
